
    <a href="#" class="btn btn-primary btn-xs customer-select"
    data-customer-id="{{ $customer->id }}"
    data-customer-name="{{ $customer->name }}"
     data-customer-email="{{ $customer->email }}"
     data-customer-phone="{{ $customer->phone }}"
     data-customer-address-1="{{ $customer->address_1 }}"
     data-customer-address_2="{{ $customer->address_2 }}"
     data-customer-city="{{ $customer->city }}"
     data-customer-country="{{ $customer->country }}"
     data-customer-postcode="{{ $customer->post_code }}"
     data-customer-name-ship="{{ $customer->ship_name }}"
     data-customer-address-1-ship="{{ $customer->ship_address_1 }}"
     data-customer-address-2-ship="{{ $customer->ship_address_2 }}"
      data-customer-city-ship="{{ $customer->ship_city }}"
    data-customer-country-ship="{{ $customer->ship_country }}"
     data-customer-postcode-ship="{{ $customer->ship_post_code }}">Select</a>
